export const Strings = {
  common: {
    refreshButton: 'רענן',
  },
  errors: {
    appCrashTitle: 'משהו השתבש',
    appCrashMessage: 'קרתה שגיאה בלתי צפויה. ננסה לתקן את זה בהקדם.',
    reloadButton: 'רענן את הדף',
  },
  auth: {
    welcomeBack: 'ברוך הבא',
    getStarted: 'להרשמה',
    loginSubtitle: 'הכנס את פרטי ההתחברות שלך כדי לגשת לחשבון',
    registerSubtitle: 'צור חשבון כדי להתחיל להשתמש באפליקציית Retro',
    usernamePlaceholder: 'שם משתמש',
    // Login-form identifier field (BUG-58) — registration is by email, so the login label says so.
    // Kept separate from usernamePlaceholder, which the phantom-conversion form still uses for a real username.
    loginIdentifierLabel: 'אימייל',
    emailPlaceholder: 'כתובת אימייל',
    firstNamePlaceholder: 'שם פרטי (אופציונלי)',
    lastNamePlaceholder: 'שם משפחה (אופציונלי)',
    passwordPlaceholder: 'סיסמה',
    loginButton: 'התחברות',
    signUpButton: 'הרשמה',
    toggleToSignUp: "אין לך חשבון? הרשם כאן",
    toggleToLogin: 'כבר יש לך חשבון? התחבר כאן',
    requiredFieldsError: 'נא למלא את כל שדות החובה.',
    emailExistsError: 'כתובת האימייל הזו כבר רשומה במערכת. אפשר להתחבר, או להירשם עם כתובת אחרת.',
    invalidCredentialsError: 'שם המשתמש או הסיסמה שגויים.',
    networkError: 'אין חיבור לשרת כרגע. נסה/י שוב בעוד רגע.',
    genericError: 'שגיאה בתהליך ההתחברות/הרשמה.',
    showPasswordLabel: 'הצג סיסמה',
    hidePasswordLabel: 'הסתר סיסמה',
    orDividerText: 'או',
    continueWithGoogleButton: 'המשך עם Google',
    googleConnectError: 'לא ניתן להתחיל התחברות עם Google כרגע. נסה/י שוב.',
    googleCallbackLoadingText: 'מתחברים עם Google...',
    googleCallbackErrorTitle: 'ההתחברות עם Google נכשלה',
    googleCallbackErrorText: 'אירעה שגיאה בתהליך ההתחברות עם Google. אפשר לנסות שוב או להתחבר עם שם משתמש וסיסמה.',
    googleCallbackBackButton: 'חזרה למסך ההתחברות',
    googleChooseRoleTitle: 'עוד צעד אחד קטן',
    googleChooseRoleSubtitle: 'בחר/י את התפקיד המקצועי שלך כדי לסיים את ההרשמה',
    googleChooseRoleButton: 'סיום הרשמה',
  },
  dashboard: {
    welcomeTitle: (name: string) => `ברוך הבא, ${name}!`,
    welcomeSubtitle: 'התחברת בהצלחה למערכת Retro.',
    loadingTeams: 'טוען את הצוותים שלך...',
    teamCreateFailedError: 'יצירת הצוות נכשלה. נסו שוב.',
    teamCreateNetworkError: 'אין חיבור לשרת כרגע. נסו שוב בעוד רגע.',
    teamsLoadError: 'לא הצלחנו לטעון את הצוותים שלך. אפשר ללחוץ על "רענן" ולנסות שוב.',
    createFirstTeamTitle: 'צור את צוות הפיתוח הראשון שלך',
    createFirstTeamDesc: "אינך שייך לאף צוות פיתוח עדיין. צור אחד למטה כדי להתחיל לאסוף הערות רטרו.",
    createTeamTitle: 'צור צוות חדש',
    closeButton: 'סגור',
    createNewTeamButton: '+ צור צוות חדש',
    accountDetailsHeader: 'פרטי חשבון',
    usernameLabel: 'שם משתמש: ',
    emailLabel: 'אימייל: ',
    creatorEmailLabel: (email: string) => `היוצר/ת: ${email}`,
    approverPickerLabel: 'מי יאשר/תאשר את הקמת הצוות?',
    approverEmailHint: 'הצוות ייווצר רק לאחר שהמאשר/ת שתבחר/י יאשר/תאשר את ההקמה מהחשבון שלו/שלה. הודעה תישלח אליו/ה במייל.',
    approverEmailRequiredError: 'צריך לבחור מי יאשר/תאשר את הקמת הצוות.',
    approverListLoading: 'טוען רשימת מאשרים...',
    approverListLoadError: 'לא ניתן לטעון את רשימת המאשרים. נסה/י שוב מאוחר יותר.',
    pendingApprovalFromLabel: (email: string) => `ממתין לאישור מ-${email}`,
    approvalInviteText: (creatorName: string) => `${creatorName} מבקש/ת את אישורך להקמת הצוות`,
    approveTeamButton: 'אשר',
    declineTeamButton: 'דחה',
    cancelPendingTeamButton: 'בטל',
    teamActionFailedError: 'הפעולה נכשלה. נסה/י שוב.',
    memberInviteText: 'הוזמנת להצטרף לצוות הזה',
  },
  teamList: {
    myTeamsHeader: 'הצוותים שלי',
    membersHeader: 'חברי הצוות',
    membersToggleLabel: (count: number) => `חברים · ${count}`,
    summaryPending: (count: number) => `${count} ממתין לאישור`,
    summaryActiveSprints: (count: number) => count === 0 ? 'אין ספרינט פעיל' : count === 1 ? 'ספרינט פעיל אחד' : `${count} ספרינטים פעילים`,
    manageMemberLabel: (name: string) => `ניהול ${name}`,
    teamAdminPrivileges: 'הרשאות מנהל צוות',
    cancelButton: 'ביטול',
    saveButton: 'שמור',
    editMemberHeader: (username: string) => `ערוך את @${username}`,
    officeLocationLabel: 'מיקום המשרד: ',
    adminBadge: 'מנהל',
    addMemberToggle: 'הוסף חבר',
    addMemberModalTitle: 'הוספת חבר לצוות',
    addMemberTabExisting: 'חבר קיים',
    addMemberTabPhantom: 'חבר פנטום',
    addMemberTabLink: 'קישור הזמנה',
    closeModalLabel: 'סגור',
    addMemberModeEmailLabel: 'לפי אימייל',
    addMemberModeLinkLabel: 'קישור הזמנה',
    addMemberPlaceholder: 'שם משתמש להזמנה לצוות',
    addMemberButton: 'שלח הזמנה',
    pendingMemberBadge: 'ממתין לאישור',
    emailInviteSentText: (email: string) => `נשלח מייל הזמנה ל-${email}`,
    phantomBadge: 'לא רשום',
    addPhantomMemberToggle: 'הוסף חבר פנטום',
    addPhantomMemberHeader: 'הוספת חבר פנטום',
    phantomFirstNameLabel: 'שם פרטי',
    phantomLastNamePlaceholder: 'שם משפחה (אופציונלי)',
    addPhantomMemberButton: 'צור חבר פנטום',
    phantomFirstNameRequiredError: 'נא למלא שם פרטי.',
    phantomMemberCreateError: 'יצירת חבר הפנטום נכשלה.',
    removeMemberButton: 'הסר',
    removeMemberConfirmText: (name: string) => `להסיר את ${name} מהצוות?`,
    removeMemberConfirmButton: 'כן, הסר',
    removeMemberCancelButton: 'ביטול',
  },
  invites: {
    manageLinksToggle: 'קישורי הזמנה',
    createLinkButton: 'צור קישור הזמנה',
    nameLabel: 'שם לקישור (אופציונלי)',
    namePlaceholder: 'למשל: לינק לצוות הפיתוח',
    unnamedLinkLabel: 'קישור ללא שם',
    expiresAtLabel: 'תאריך תפוגה (אופציונלי)',
    maxUsesLabel: 'מספר שימושים מקסימלי (אופציונלי)',
    linkCreatedText: 'הקישור נוצר בהצלחה',
    linkCreatedSubtext: 'שתפו את הקישור הבא כדי להצטרף לצוות:',
    copyLinkButton: 'העתק קישור',
    linkCopiedText: 'הועתק!',
    copyFailedError: 'ההעתקה נכשלה. אפשר לסמן את הקישור ולהעתיק ידנית.',
    loadError: 'לא הצלחנו לטעון את קישורי ההזמנה. נסו לרענן.',
    expiresAtFormatError: 'תאריך התפוגה צריך להיות בפורמט YYYY-MM-DD.',
    expiresAtPastError: 'תאריך התפוגה חייב להיות היום או בעתיד.',
    maxUsesInvalidError: 'מספר השימושים חייב להיות מספר שלם חיובי (1 ומעלה).',
    revokeFailedError: 'ביטול הקישור נכשל. נסו שוב.',
    createFailedError: 'יצירת הקישור נכשלה.',
    backToAppButton: 'חזרה לאפליקציה',
    revokeButton: 'מחק קישור',
    noLinksText: 'לא נוצרו קישורי הזמנה עדיין.',
    statusActive: 'פעיל',
    statusRevoked: 'בוטל',
    statusExpired: 'פג תוקף',
    statusExhausted: 'נוצל במלואו',
    usesLabel: (used: number, max: number | null) => max === null ? `${used} שימושים` : `${used}/${max} שימושים`,
    loadingInviteText: 'בודק/ת את ההזמנה...',
    invalidInviteTitle: 'הזמנה לא תקפה',
    joinTeamPromptText: (teamName: string) => `הוזמנת להצטרף לצוות "${teamName}" — הירשם/י או התחבר/י כדי להצטרף`,
    joiningTeamText: 'מצטרף/ת לצוות...',
    joinedTeamText: 'הצטרפת לצוות בהצלחה! מעביר/ה אותך לדשבורד...',
    joinFailedError: 'ההצטרפות לצוות נכשלה.',
    sendConversionLinkButton: 'שלח קישור הרשמה',
    conversionLinkCreatedText: 'קישור ההרשמה נוצר בהצלחה',
    conversionLinkCreatedSubtext: 'שתפו את הקישור הבא עם חבר הצוות כדי שיוכל/תוכל להירשם ולהשלים את החשבון:',
    conversionLinkCreateError: 'יצירת קישור ההרשמה נכשלה.',
    phantomConversionTitle: (teamName: string) => `השלמת הרשמה לצוות "${teamName}"`,
    phantomConversionSubtitle: 'מלא/י את הפרטים הבאים כדי להשלים את ההרשמה ולהתחבר לחשבון שלך.',
    phantomConversionSubmitButton: 'השלם הרשמה',
    phantomConversionError: 'השלמת ההרשמה נכשלה. נסה/י שוב.',
  },
  // Team-settings panel (team-settings-panel.tsx) — admin/TEAM_LEADER-only, opens inline on a
  // team's own card. Unifies what used to be split across this panel's category-only predecessor
  // and the global /settings page's per-team name/office edit list (removed 2026-09-18 in favor
  // of this single per-team entry point).
  teamSettingsPanel: {
    title: 'הגדרות צוות',
    teamDetailsSectionTitle: 'פרטי הצוות',
    teamNameLabel: 'שם הצוות',
    teamNamePlaceholder: 'הכנס שם צוות',
    teamOfficeLabel: 'משרד ראשי / מיקום',
    teamOfficePlaceholder: 'הכנס מיקום/משרד ראשי',
    editTeamDetailsButton: 'ערוך',
    saveTeamDetailsButton: 'שמור שינויים',
    teamNameRequiredError: 'שם צוות הוא שדה חובה.',
    teamDetailsUpdatedText: 'פרטי הצוות עודכנו בהצלחה.',
    teamDetailsUpdateErrorText: 'עדכון פרטי הצוות נכשל.',
  },
  // Feature 3 (team comment categories, product-backlog/03-team-comment-categories.md §3.2):
  // strings for the categories section of the team-settings panel (team-settings-panel.tsx).
  categoryManagement: {
    categorySectionTitle: 'קטגוריות הערות',
    loadingText: 'טוען קטגוריות...',
    loadErrorText: 'טעינת הקטגוריות נכשלה.',
    emptyText: 'אין קטגוריות עדיין.',
    defaultBadge: 'דיפולטית',
    customBadge: 'מותאמת אישית',
    createButton: '+ הוסף קטגוריה',
    newCategoryLabel: 'שם הקטגוריה',
    newCategoryPlaceholder: 'למשל: תיאום בין צוותים',
    labelRequiredError: 'יש להזין שם קטגוריה.',
    createErrorText: 'יצירת הקטגוריה נכשלה.',
    usageCountLabel: (n: number) => n === 0 ? 'לא נעשה בה שימוש' : n === 1 ? 'שימוש אחד' : `${n} שימושים`,
    sprintFilterAllLabel: 'כל הספרינטים',
    sprintFilterSelectedLabel: (selected: number, total: number) => `${selected} מתוך ${total} ספרינטים`,
    sprintFilterTitle: 'סנן ספירת שימושים לפי ספרינטים',
  },
  sprints: {
    header: 'ספרינטים ולוחות רטרו',
    newSprintButton: '+ פתח ספרינט',
    cancelButton: '✕ סגור',
    createSprintHeader: 'פתיחת לוח רטרו חדש',
    sprintNamePlaceholder: 'שם הספרינט (למשל ספרינט 1)',
    descriptionPlaceholder: 'תיאור (אופציונלי)',
    startDateLabel: 'תאריך התחלה',
    endDateLabel: 'תאריך סיום',
    openRetroButton: 'פתח ספרינט רטרו',
    noSprintsTextAdmin: 'לא נוצרו ספרינטים עדיין. השתמש בכפתור "+ פתח ספרינט" כדי ליצור אחד!',
    noSprintsTextMember: 'לא נוצרו ספרינטים עדיין. המתן שמנהל הצוות יפתח מפגש רטרו.',
    enterRetroButton: 'כניסה ללוח ←',
    endBeforeStartError: 'תאריך הסיום לא יכול להיות לפני תאריך ההתחלה.',
    invalidDateError: 'תאריך לא תקין. הזינו תאריך בפורמט YYYY-MM-DD (למשל 2026-10-09).',
    requiredFieldsError: 'שם, תאריך התחלה ותאריך סיום הם שדות חובה.',
    createSprintErrorText: 'שגיאה בפתיחת ספרינט רטרו.',
    loadError: 'לא הצלחנו לטעון את הספרינטים. אפשר ללחוץ על "רענן" ולנסות שוב.',
    noSprintsInFilterText: 'אין ספרינטים להצגה בסינון הזה.',
    filterButtonLabel: 'סינון ספרינטים',
    filterOptions: { all: 'הכל', active: 'פעילים', closed: 'סגורים' },
    recentHeader: 'הסתיימו לאחרונה',
    endedBadge: 'הסתיים',
    activeBadge: 'פעיל',
    startsInBadge: (days: number) => days <= 1 ? 'מתחיל מחר' : `מתחיל בעוד ${days} ימים`,
    progressText: (day: number, total: number) => `יום ${day} מתוך ${total}`,
    expiredHeader: (count: number) => `ספרינטים שהסתיימו · ${count}`,
  },
  retroBoard: {
    backButton: '← חזרה לדשבורד',
    editSprintButton: 'ערוך ספרינט',
    editSprintHeader: 'עריכת פרטי ספרינט',
    editSprintErrorText: 'שמירת השינויים נכשלה. נסו שוב.',
    writeNoteHeader: 'כתוב הערת רטרו',
    keepLabel: 'שימור',
    improveLabel: 'שיפור',
    keepColumnHeader: 'שימור',
    improveColumnHeader: 'שיפור',
    emptyKeepText: 'אין הערות שימור עדיין.',
    emptyImproveText: 'אין הערות שיפור עדיין.',
    loadCommentsError: 'לא הצלחנו לטעון את ההערות. אפשר ללחוץ על "רענן" ולנסות שוב.',
    anonymousToggleHint: 'מפרסם/ת בתור',
    identifiedToggleLabel: 'בשם מלא',
    anonymousToggleLabel: 'אנונימי',
    postNoteButton: 'פרסם הערה',
    spinLabel: 'לחצו כדי להחליף בין שימור לשיפור',
    loadingBoard: 'טוען לוח רטרו...',
    anonymousAuthor: 'אנונימי',
    notePlaceholderKeep: 'מה היה טוב בספרינט הזה?',
    notePlaceholderImprove: 'מה היית משנה בספרינט הבא?',
    categoryLabel: 'קטגוריה',
    categoryNone: 'ללא קטגוריה',
    // Feature 3 (team comment categories, product-backlog/03-team-comment-categories.md §3.2,
    // decision "לא בטיפול"/§3.2 last item): as of the per-team TeamCommentCategory table, this
    // object is ONLY the default-seed list source for the backend (teams.service.ts::create +
    // backfill-team-comment-categories.js) — it is no longer the UI's runtime source of truth.
    // The category picker, filter bar, and comment card all read categories dynamically from
    // GET /teams/:teamId/categories instead.
    categories: {
      SPRINT_SETUP: 'התארגנות לספרינט',
      PRE_PLANNING: 'פרה-פלנינג',
      PLANNING: 'פלנינג',
      ONGOING_WORK: 'עבודה שוטפת',
      TESTING: 'בדיקות',
      AVAILABILITY: 'זמינות',
      ESTIMATIONS: 'תמחורים',
      SPECIFICATIONS: 'איפיונים',
      TASK_DISTRIBUTION: 'חלוקת משימות',
      PERSONAL: 'אישי',
      FUN: 'הוואי ובידור',
      GENERAL: 'כללי',
      TECHNICAL: 'טכני',
    } as Record<string, string>,
    filterSectionLabel: 'סינון הערות',
    searchFieldLabel: 'חיפוש',
    filterAllCategoriesLabel: 'כל הקטגוריות',
    categoriesSelectedLabel: (count: number) => count === 1 ? 'קטגוריה אחת נבחרה' : `${count} קטגוריות נבחרו`,
    searchPlaceholder: 'חיפוש בתוך ההערות...',
    clearFiltersLabel: 'נקה סינון',
    noMatchingCommentsText: 'אין הערות התואמות לסינון',
    highlightButton: 'הדגש הערה',
    unhighlightButton: 'בטל הדגשה',
    highlightedOnlyFilterLabel: 'מודגשות בלבד',
    postOnBehalfLabel: 'בשם:',
    postOnBehalfMeOption: 'אני',
    postOnBehalfOtherOption: 'בשם מישהו אחר',
    postedOnBehalfIndicator: (authorName: string, adminName: string) => `הוזן/ה בשם ${authorName} על ידי ${adminName}`,
    // Feature 5 (sprint length audit log, product-backlog/05-sprint-length-audit-log.md §5.2):
    // history panel visible only to admin/TEAM_LEADER (assertCanManageTeamContent, mirrored
    // client-side the same way canHighlight/canPostOnBehalf already are).
    editReasonLabel: 'סיבה לשינוי (אופציונלי)',
    editReasonPlaceholder: 'למשל: דחיית תאריך הסיום בעקבות חג',
    lengthHistoryShowButton: 'היסטוריית שינויי אורך',
    lengthHistoryHideButton: 'הסתר היסטוריית שינויים',
    lengthHistoryTitle: 'היסטוריית שינויי אורך ספרינט',
    lengthHistoryLoadingText: 'טוען היסטוריה...',
    lengthHistoryErrorText: 'טעינת ההיסטוריה נכשלה.',
    lengthHistoryEmptyText: 'אין עדיין שינויים מתועדים.',
    lengthHistoryCreatedInitiallyText: 'נוצר לראשונה',
    lengthHistoryPreviousLengthLabel: 'אורך קודם',
    lengthHistoryNewLengthLabel: 'אורך חדש',
    lengthHistoryDaysLabel: (days: number) => (days === 1 ? 'יום אחד' : `${days} ימים`),
    lengthHistoryDatesLabel: (start: string, end: string) => `${start} – ${end}`,
    lengthHistoryReasonLabel: 'סיבה:',
  },
  settings: {
    pageTitle: 'הגדרות מערכת',
    pageSubtitle: 'ניהול פרטים אישיים, צוותים ואפשרויות מערכת נוספות.',
    backToHomeButton: '← חזרה לראשי',
    createTeamSectionTitle: 'יצירת צוות חדש',
    googleCalendarCardTitle: 'יומן Google',
    googleCalendarCardSubtitle: 'חבר את חשבון ה-Google האישי שלך כדי שתאריכי הספרינטים יופיעו ביומן שלך אוטומטית.',
    googleCalendarStatusLoading: 'בודק סטטוס חיבור...',
    googleCalendarNotConnectedText: 'לא מחובר',
    googleCalendarConnectedLabel: (email: string) => `מחובר כ-${email}`,
    googleCalendarConnectButton: 'חבר יומן Google',
    googleCalendarDisconnectButton: 'נתק חיבור',
    googleCalendarConnectedMessage: 'יומן Google חובר בהצלחה.',
    googleCalendarDisconnectedMessage: 'החיבור ליומן Google נותק.',
    googleCalendarStatusLoadError: 'לא הצלחנו לבדוק את סטטוס החיבור ליומן Google. נסו לרענן את הדף.',
    googleCalendarConnectError: 'החיבור ליומן Google נכשל או בוטל. אפשר לנסות שוב.',
    googleCalendarDisconnectError: 'ניתוק החיבור נכשל. אפשר לנסות שוב.',
    telegramCardTitle: 'טלגרם',
    telegramCardSubtitle: 'קשרי את חשבון הטלגרם שלך כדי להזין תגובות רטרו ישירות מהצ\'אט עם הבוט.',
    telegramStatusLoading: 'בודק סטטוס חיבור...',
    telegramNotConnectedText: 'לא מחובר',
    telegramConnectedText: 'מחובר',
    telegramDisconnectButton: 'נתק חיבור',
    telegramLinkedMessage: 'חשבון הטלגרם קושר בהצלחה.',
    telegramUnlinkedMessage: 'החיבור לטלגרם נותק.',
    telegramLinkError: 'קישור הטלגרם נכשל. אפשר לנסות שוב.',
    telegramUnlinkError: 'ניתוק החיבור נכשל. אפשר לנסות שוב.',
    telegramWidgetUnavailableText: 'קישור טלגרם אינו מוגדר כרגע.',
    telegramNativeUnavailableText: 'קישור טלגרם זמין באתר בלבד.',
    telegramOpenInBrowserButton: 'פתח בדפדפן',
    googleCalendarNativeUnavailableText: 'חיבור יומן Google זמין באתר בלבד.',
    logoutButton: 'יציאה',
    logoutDescription: 'התנתקות מהחשבון במכשיר הזה.',
    logoutSectionTitle: 'חשבון',
    profileCardTitle: 'עדכון פרטים אישיים',
    firstNameLabel: 'שם פרטי',
    firstNamePlaceholder: 'הכנס שם פרטי',
    lastNameLabel: 'שם משפחה',
    lastNamePlaceholder: 'הכנס שם משפחה',
    emailLabel: 'כתובת אימייל',
    emailPlaceholder: 'הכנס כתובת אימייל',
    saveProfileButton: 'שמור שינויים',
    appearanceCardTitle: 'מראה',
    appearanceCardSubtitle: 'נשמר לכל משתמש בנפרד ומוחל על כל האפליקציה',
    modeLabel: 'מצב תצוגה',
    modeHint: '״מערכת״ עוקב אחרי הגדרות המכשיר',
    modeLight: 'בהיר',
    modeDark: 'כהה',
    modeSystem: 'מערכת',
    schemeLabel: 'סכימת צבע',
    schemeHint: 'משנה את האקסנט בלבד. הניטרלים נשארים זהים בכל הסכימות',
    schemeNames: {
      blue: 'כחול',
      cyan: 'תכלת',
      teal: 'טורקיז',
      green: 'ירוק',
      amber: 'ענבר',
      rose: 'ורוד',
      purple: 'סגול',
      graphite: 'גרפיט',
    },
    densityLabel: 'צפיפות',
    densityHint: 'מכפיל את סקאלת הריווח, לא את גדלי הגופן',
    densityCompact: 'קומפקטי',
    densityRegular: 'רגיל',
  },
  // BUG-33: loading / failure states of the sprint routes (board, summary, memory), which fetch
  // their own sprint + team by id so a refresh or a shared link works.
  sprintRoute: {
    loading: 'טוען את הספרינט...',
    loadError: 'לא הצלחנו לטעון את הספרינט. אפשר ללחוץ על "נסה שוב".',
    notFoundTitle: 'הספרינט לא נמצא',
    notFoundText: 'ייתכן שהקישור שגוי, שהספרינט נמחק, או שאין לך גישה לצוות שלו.',
    retryButton: 'נסה שוב',
    backToDashboardButton: 'חזרה לראשי',
  },
  memoryBoard: {
    openButton: 'משחק זיכרון',
    backButton: '← חזרה ללוח',
    pageTitle: 'משחק זיכרון',
    pageSubtitle: 'לחיצה הופכת קלף וחושפת מה כתוב בו. לחיצה כפולה גם מגדילה אותו.',
    keepCanvasHeader: 'שימור',
    improveCanvasHeader: 'שיפור',
    emptyKeepText: 'אין קלפי שימור להצגה.',
    emptyImproveText: 'אין קלפי שיפור להצגה.',
    loadError: 'לא הצלחנו לטעון את הקלפים. אפשר ללחוץ על "רענן" ולנסות שוב.',
    loadingBoard: 'טוען קלפים...',
    flipCardHint: 'קלף הפוך, לחצו כדי לחשוף',
  },
  sprintSummary: {
    openButton: 'סיכום ספרינט',
    backButton: '← חזרה ללוח',
    pageTitle: 'סיכום ספרינט',
    pageSubtitle: 'הורדת מצגת עם כל התגובות של הספרינט, מאורגנות לפי קטגוריה.',
    totalCommentsLabel: 'סה"כ תגובות',
    keepCountLabel: 'שימור',
    improveCountLabel: 'שיפור',
    byCategoryHeader: 'לפי קטגוריה',
    templateLabel: 'עיצוב המצגת',
    noCommentsText: 'אין עדיין תגובות בספרינט זה.',
    loadError: 'לא הצלחנו לטעון את נתוני הסיכום. אפשר ללחוץ על "רענן" ולנסות שוב.',
    downloadButton: 'הורד מצגת (PPTX)',
    downloadingButton: 'מכין מצגת...',
    downloadErrorText: 'שגיאה בהפקת המצגת. נסו שוב.',
    downloadSuccessNativeText: 'המצגת נשמרה בהצלחה.',
  },
};
