export const Strings = {
  auth: {
    welcomeBack: 'ברוך הבא',
    getStarted: 'להרשמה',
    loginSubtitle: 'הכנס את פרטי ההתחברות שלך כדי לגשת לחשבון',
    registerSubtitle: 'צור חשבון כדי להתחיל להשתמש באפליקציית Retro',
    usernamePlaceholder: 'שם משתמש',
    emailPlaceholder: 'כתובת אימייל',
    firstNamePlaceholder: 'שם פרטי (אופציונלי)',
    lastNamePlaceholder: 'שם משפחה (אופציונלי)',
    passwordPlaceholder: 'סיסמה',
    loginButton: 'התחברות',
    signUpButton: 'הרשמה',
    toggleToSignUp: "אין לך חשבון? הרשם כאן",
    toggleToLogin: 'כבר יש לך חשבון? התחבר כאן',
    requiredFieldsError: 'נא למלא את כל שדות החובה.',
  },
  dashboard: {
    welcomeTitle: (name: string) => `ברוך הבא, ${name}!`,
    welcomeSubtitle: 'התחברת בהצלחה למערכת Retro.',
    loadingTeams: 'טוען את הצוותים שלך...',
    createFirstTeamTitle: 'צור את צוות הפיתוח הראשון שלך',
    createFirstTeamDesc: "אינך שייך לאף צוות פיתוח עדיין. צור אחד למטה כדי להתחיל לאסוף הערות רטרו.",
    createTeamTitle: 'צור צוות חדש',
    closeButton: 'סגור',
    createNewTeamButton: '+ צור צוות חדש',
    accountDetailsHeader: 'פרטי חשבון',
    usernameLabel: 'שם משתמש: ',
    emailLabel: 'אימייל: ',
  },
  teamList: {
    membersHeader: (count: number) => `חברים (${count}):`,
    teamAdminPrivileges: 'הרשאות מנהל צוות',
    cancelButton: 'ביטול',
    saveButton: 'שמור',
    editMemberHeader: (username: string) => `ערוך את @${username}`,
    officeLocationLabel: 'מיקום המשרד: ',
    roleLabel: (role: string, isAdmin: boolean) => `[${role}]${isAdmin ? ' • מנהל' : ''}`,
    addMemberPlaceholder: 'שם משתמש להוספה לצוות',
    addMemberButton: 'הוסף לצוות',
  },
  sprints: {
    header: 'ספרינטים ולוחות רטרו',
    newSprintButton: '+ פתח ספרינט',
    cancelButton: '✕ סגור',
    createSprintHeader: 'פתיחת לוח רטרו חדש',
    sprintNamePlaceholder: 'שם הספרינט (למשל ספרינט 1)',
    descriptionPlaceholder: 'תיאור (אופציונלי)',
    startDateLabel: 'תאריך התחלה',
    endDateLabel: 'תאריך סיום',
    openRetroButton: 'פתח ספרינט רטרו',
    noSprintsTextAdmin: 'לא נוצרו ספרינטים עדיין. השתמש בכפתור "+ פתח ספרינט" כדי ליצור אחד!',
    noSprintsTextMember: 'לא נוצרו ספרינטים עדיין. המתן שמנהל הצוות יפתח מפגש רטרו.',
    enterRetroButton: 'כניסה ללוח ←',
  },
  retroBoard: {
    backButton: '← חזרה לדשבורד',
    writeNoteHeader: 'כתוב הערת רטרו',
    keepLabel: 'שימור',
    improveLabel: 'שיפור',
    keepColumnHeader: 'שימור 🟢',
    improveColumnHeader: 'שיפור 🔴',
    emptyKeepText: 'אין הערות שימור עדיין.',
    emptyImproveText: 'אין הערות שיפור עדיין.',
    anonymousToggleHint: 'לחצו כדי לפרסם את ההערה הזו במצב אנונימי',
    postNoteButton: 'פרסם הערה',
    spinLabel: 'לחצו כדי להחליף בין שימור לשיפור',
    loadingBoard: 'טוען לוח רטרו...',
    anonymousAuthor: 'אנונימי',
    notePlaceholderKeep: 'מה היה טוב בספרינט הזה?',
    notePlaceholderImprove: 'מה היית משנה בספרינט הבא?',
    categoryLabel: 'קטגוריה',
    categoryNone: 'ללא קטגוריה',
    categories: {
      SPRINT_SETUP: 'התארגנות לספרינט',
      PRE_PLANNING: 'פרה-פלנינג',
      PLANNING: 'פלנינג',
      ONGOING_WORK: 'עבודה שוטפת',
      TESTING: 'בדיקות',
      AVAILABILITY: 'זמינות',
      ESTIMATIONS: 'תמחורים',
      SPECIFICATIONS: 'איפיונים',
      TASK_DISTRIBUTION: 'חלוקת משימות',
      PERSONAL: 'אישי',
      FUN: 'הוואי ובידור',
      GENERAL: 'כללי',
      TECHNICAL: 'טכני',
    } as Record<string, string>,
  }
};
